name: Dev
on:
  push:
    branches: master

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
        env:
          VUE_APP_API_KEY: AIzaSyDHBWKZq0qtEIjB1wRBeXaMz0rUgd7dbvo
          VUE_APP_AUTH_DOMAIN: dev-servak.firebaseapp.com
          VUE_APP_PROJECT_ID: dev-servak
          VUE_APP_API_URL: https://api.lifespan.plush.dev
      - name: Push to ls-client.dev-team.club
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: dev-servak
          target: front-ls-client
          channelId: live
